apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: electronics-store-hpa
  namespace: electronics-store-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: electronics-store-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
