apiVersion: v1
kind: Service
metadata:
  name: electronics-store-service
  namespace: electronics-store-namespace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: electronics-store
